name: '🔎 Python Tests'

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-tests-${{ github.ref }}-pytest
  cancel-in-progress: true

jobs:
  python-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: setup_python
        name: Set up Python ${{ matrix.python-version }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Lint Jupyter Notebooks with nbqa black
        run: pipenv run nbqa black ./notebooks

      - name: Lint Jupyter Notebooks with nbqa isort
        run: pipenv run nbqa isort ./notebooks --float-to-top

      - name: Lint Jupyter Notebooks with nbqa blacken-docs
        run: pipenv run nbqa blacken-docs ./notebooks --nbqa-md --nbqa-diff

      - name: Convert and run Jupyter Notebooks
        run: |
          for notebook in $(find . -name "*.ipynb"); do
            pipenv run jupyter nbconvert --to notebook --execute $notebook 
          done
